apiVersion: apps/v1

kind: Deployment

metadata:
  name: ngnix-deployment-2

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: sainiprakhar23/nginx-practise-2:1
          ports:
            - containerPort: 80